name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: false
          fetch-depth: 0
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "v0.145.0"
    - name: Build and Deploy
      run: |
        hugo -F --cleanDestinationDir
        mkdir -p public
        cp -r public/* ./
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        EXTERNAL_REPOSITORY: iguri/iguri.github.io
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./
        commit_message: ${{ github.event.head_commit.message }}
